<a href="https://colab.research.google.com/github/arijitar/Machine-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [1]:
import numpy as np

In [9]:
A = np.round(10*np.random.rand(2, 3))
A

array([[8., 7., 6.],
       [1., 8., 5.]])

In [10]:
A+3

array([[11., 10.,  9.],
       [ 4., 11.,  8.]])

In [11]:
A+ np.arange(2).reshape(2,1)

array([[8., 7., 6.],
       [2., 9., 6.]])

In [12]:
A

array([[8., 7., 6.],
       [1., 8., 5.]])

In [13]:
B = np.round(10*np.random.rand(2,2))

In [14]:
A

array([[8., 7., 6.],
       [1., 8., 5.]])

In [15]:
B

array([[7., 6.],
       [6., 6.]])

In [16]:
C = np.hstack((A,B))
C

array([[8., 7., 6., 7., 6.],
       [1., 8., 5., 6., 6.]])

In [17]:
A = np.random.permutation(np.arange(10))
A

array([0, 3, 7, 5, 2, 1, 4, 6, 8, 9])

In [19]:
np.sort(A)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
A.sort()

In [21]:
A = A[::-1]

In [22]:
A

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [23]:
A = np.array(["abc", "how are you", "u765", "13er"])

In [26]:
A.sort()
A

array(['13er', 'abc', 'how are you', 'u765'], dtype='<U11')

# Numpy(Speed: ufuncs)

In [31]:
B = np.random.rand(1000000)

In [32]:
%timeit sum(B)
%timeit np.sum(B) #B.sum ()

105 ms ± 15.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
468 µs ± 127 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [30]:
def mysum(G):
   s = 0
   for x in G:
      s += x
   return s

In [35]:
%timeit mysum(B)

148 ms ± 36.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
